module.exports = {
  photos_all:             'All photos',
  photo_taken:            'Taken (Y.m.d)',
  photo_gps:              'Gps coordinates',
  photo_title_ru:         'Russian title',
  photo_title_en:         'English title',
  photo_restore:          'restore',
  photo_delete:           'delete',
  photo_edit:             'edit',
  photo_update:           'Update photo',
  selected_photos_attach: 'Attach %selected% photo',
  selected_photos_abort:  'Cancel',
  collection_restore:     'restore',
  collection_delete:      'delete',
  collection_edit:        'edit',
  collection_abort:       'cancel',
  collection_add:         'Add new album',
  collections_expand:     'Show all albums',
  collections_collapse:   'Hide albums',
  collections_back:       '← All photos',
  tag_iso:                'ISO',
  tag_shutter_speed:      'Shutter speed',
  tag_aperture:           'Aperture',
  tag_camera:             'Camera',
  tag_lens:               'Lens',
  tag_category:           'Category',
};