module.exports = {
  photos_all:             'All photos',
  photo_restore:          'restore',
  photo_delete:           'delete',
  photo_edit:             'edit',
  selected_photos_attach: 'Attach %selected% photo',
  selected_photos_abort:  'Cancel',
  collection_restore:     'restore',
  collection_delete:      'delete',
  collection_edit:        'edit',
  collection_abort:       'cancel',
  collection_add:         'Add new album',
  collections_expand:     'Show all albums',
  collections_collapse:   'Hide albums',
  collections_back:       '← All photos',
};