module.exports = {
  photos_all:             'Все фотографии',
  photo_taken:            'Дата (гг.мм.дд)',
  photo_gps:              'GPS координаты',
  photo_title_ru:         'Русский заголовок',
  photo_title_en:         'Английский заголовок',
  photo_restore: 					'восстановить',
  photo_delete:  					'удалить',
  photo_edit:       			'инфо',
  photo_update:           'Обновить фото',
  selected_photos_attach: 'Прикрепить %selected% фото',
  selected_photos_abort:  'Отменить',
  collection_restore:     'восстановить',
  collection_delete:      'удалить',
  collection_edit:        'изменить',
  collection_abort:       'отмена',
  collection_add:         'Добавить альбом',
  collections_expand:     'Показать все альбомы',
  collections_collapse:   'Скрыть альбомы',
  collections_back:       '← Все фотографии',
  tag_iso:                'ISO',
  tag_shutter_speed:      'Выдержка',
  tag_aperture:           'Диафрагма',
  tag_camera:             'Камера',
  tag_lens:               'Объектив',
  tag_category:           'Категория',
};